<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.0.0.309
*/

require_once('form_process.php');

$form = array(
	'subject' => 'BOOK NOW Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => 'reservation-confirmation.html',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'tinowebdesign@gmail.com',
		'to' => 'tinowebdesign@gmail.com'
	),
	'fields' => array(
		'custom_U2465' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Name*',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Name*\' is required.'
			)
		),
		'Email' => array(
			'order' => 3,
			'type' => 'email',
			'label' => 'Email*',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email*\' is required.',
				'format' => 'Field \'Email*\' has an invalid email.'
			)
		),
		'custom_U2511' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Custom',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Custom\' is required.'
			)
		),
		'custom_U2542' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Phone*',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Phone*\' is required.'
			)
		),
		'custom_U2546' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Alternate Phone',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U2633' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Event Date*',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U2639' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Party Name*',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Party Name*\' is required.'
			)
		),
		'custom_U2736' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Estimated # of Guests',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Estimated # of Guests\' is required.'
			)
		),
		'custom_U2740' => array(
			'order' => 11,
			'type' => 'string',
			'label' => 'Coupon Code',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Coupon Code\' is required.'
			)
		),
		'custom_U2856' => array(
			'order' => 10,
			'type' => 'radiogroup',
			'label' => 'Time* (Call in for additional slots)',
			'required' => true,
			'optionItems' => array(
				'9:00am - 11:00pm',
				'11:00am - 1:00am',
				'1:00pm - 3:00pm',
				'3:00pm - 5:00pm',
				'5:00pm - 7:00pm',
				'7:00pm - 9:00pm',
				'9:00pm - 11:00pm'
			),
			'errors' => array(
				'required' => 'Field \'Time* (Call in for additional slots)\' is required.',
				'format' => 'Field \'Time* (Call in for additional slots)\' has an invalid value.'
			)
		),
		'custom_U2482' => array(
			'order' => 6,
			'type' => 'radiogroup',
			'label' => 'Package*',
			'required' => true,
			'optionItems' => array(
				'Classic',
				'Deluxe',
				'Ultimate'
			),
			'errors' => array(
				'required' => 'Field \'Package*\' is required.',
				'format' => 'Field \'Package*\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
